"""
Section D — AI-Augmented Learning: Original Uncorrected AI Code
Buggy code generated by AI tool prior to code review and debugging.
"""
from sentence_transformers import SentenceTransformer
import faiss

# Bug 1: Hardcoded fixed character slicing cuts mid-sentence without word boundaries
def get_chunks(text):
    return [text[i:i+200] for i in range(0, len(text), 200)]

policy_text = "QuickBite refund policy states missing items receive 100% refund within 5 days."
chunks = get_chunks(policy_text)

model = SentenceTransformer('all-MiniLM-L6-v2')
embeddings = model.encode(chunks)

index = faiss.IndexFlatL2(384)
index.add(embeddings)

def ask(query, k=5):
    # Bug 2: No boundary check when k (5) > total chunks (len=1) -> causes Index Error or invalid access
    q_vec = model.encode([query])
    D, I = index.search(q_vec, k)
    
    # Bug 3: Prompt lacks fallback instruction and strict context boundary
    context = "\n".join([chunks[i] for i in I[0]])
    prompt = f"Context: {context}\nQuestion: {query}\nAnswer:"
    return prompt

while True:
    # Bug 4: No whitespace stripping on user input ('quit  ' fails)
    user_input = input("Ask question: ")
    if user_input == "quit":
        break
    print(ask(user_input))
